#cloud-config

package_upgrade: true

disk_setup:
  /dev/disk/azure/scsi1/lun10:
    table_type: 'gpt'
    layout:
      - 50
      - 50
    overwrite: true

fs_setup:
  - label: runs
    device: '/dev/disk/azure/scsi1/lun10'
    filesystem: 'ext4'
    partition: 1
  - label: inputs
    device: '/dev/disk/azure/scsi1/lun10'
    filesystem: 'ext4'
    partition: 2

mounts:
  - [ "/dev/disk/azure/scsi1/lun10-part1", "/data/runs", auto, "defaults,nofail" ]
  - [ "/dev/disk/azure/scsi1/lun10-part2", "/data/input", auto, "defaults,nofail" ]

# runcmd:
#  - [ mkdir, /data/input ]
#  - [ mkdir, /data/runs ] 
#  - [ chown, -R, "azureuser:azureuser", /data ]

# write_files:
# - path: /home/azureuser/.ncbi/user-settings.mkfg
#   permissions: '0644'
#   content: |
#     /LIBS/GUID = "35a9977e-ac83-4b06-8751-ea61537984a7"
#     /config/default = "false"
#     /repository/user/ad/public/apps/file/volumes/flatAd = "."
#     /repository/user/ad/public/apps/refseq/volumes/refseqAd = "."
#     /repository/user/ad/public/apps/sra/volumes/sraAd = "."
#     /repository/user/ad/public/apps/sraPileup/volumes/ad = "."
#     /repository/user/ad/public/apps/sraRealign/volumes/ad = "."
#     /repository/user/ad/public/root = "."
#     /repository/user/default-path = "/home/azureuser/ncbi"
