parameters:
- name: JOB_PREFIX
  displayName: 'Job prefix used to distinquish workloads'
  type: string
  default: "fmc"

- name: VMSIZE
  displayName: 'VM Size'
  type: string
  default: D16as_v4
  values:
  - D96as_v4
  - D64as_v4
  - D48as_v4
  - D32as_v4
  - D16as_v4
  - D8as_v4

- name: STORAGE_ACCOUNT
  displayName: 'Storage Account'
  type: string
  default: "datastorage2429sa"

- name: INPUT_CONTAINER
  displayName: 'Input Container'
  type: string
  default: "input"

- name: INPUT_PATH
  displayName: 'Input Path in Container'
  type: string
  default: "*.fastq"

- name: OUTPUT_CONTAINER
  displayName: 'Output Container'
  type: string
  default: "output"

- name: OUTPUT_PATH
  displayName: 'Output Path in Container'
  type: string
  default: "."

- name: GENOME_SIZE
  displayName: 'Size of Genome to use in calculations'
  type: string
  default: "5m"

- name: DESTROY
  displayName: 'Destroy infra after successful run?'
  type: boolean
  default: true

- name: STOPVM
  displayName: 'Stop VM after job?'
  type: boolean
  default: true

- name: SNAPSHOT
  displayName: 'Snapshot data disk after successful run?'
  type: boolean
  default: false

- name: BASTION
  displayName: 'Create a bastion host to connect?'
  type: boolean
  default: false

- name: DEBUG
  displayName: 'Output DEBUG information?'
  type: boolean
  default: false

variables:
- name: DECODE_PERCENTS
  value: false
- group: AZURE_INFO

trigger: none
pr: none

jobs:
- job: sequencing
  timeoutInMinutes: 0

  steps:
  - script: |
      set -x
      echo ${{parameters.JOB_PREFIX}}
      echo ${{parameters.INPUT_PATH}}
      echo ${{parameters.STORAGE_ACCOUNT}}
      echo ${{parameters.JOB_PREFIX}}
      echo ${{parameters.GENOME_SIZE}}
      echo ${{parameters.OUTPUT_CONTAINER}}
    displayName: 'Echo Parameters'

