trigger: none
pr: none

jobs:
- job: githubsync
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  # This script pulls all the branches EXCEPT main from GitHub and pushes them to ADO repos 
  - checkout: self
    persistCredentials: true

  - script: |
      git remote add github https://github.com/brentmcconnell/terraform-fmc.git
      git ls-remote --heads github | grep -oE "[^\/]+$" | while read remote; do git fetch github "$remote":"gh_$remote"; done
      git branch | grep "gh" | while read branch; do git push origin $branch ; done
    displayName: 'Pull remote branches from Github add add to repo'
