parameters:
- name: JOB_PREFIX
  displayName: 'Job prefix used to distinquish workloads'
  type: string
  default: "fmc"

- name: INPUT_CONTAINER
  displayName: 'Input Container Name'
  type: string
  default: "input"

- name: VMSIZE
  displayName: 'VM Size'
  type: string
  default: D16as_v4
  values:
  - D96as_v4
  - D64as_v4
  - D48as_v4
  - D32as_v4
  - D16as_v4
  - D8as_v4

variables:
- name: DECODE_PERCENTS
  value: false


trigger: none
pr: none

jobs:
- job: sequencing
  timeoutInMinutes: 0

  steps: 
  - ${{ each parameter in parameters }}:
    - script: echo ${{ parameter.Key }} - ${{ parameter.Value }}

  - script: |
      sleep 1800