#cloud-config

package_upgrade: true

disk_setup:
  /dev/disk/azure/scsi1/lun10:
    table_type: 'gpt'
    layout:
      - 100
    overwrite: true

fs_setup:
  - label: data
    device: '/dev/disk/azure/scsi1/lun10'
    filesystem: 'ext4'
    partition: 1

mounts:
  - [ "/dev/disk/azure/scsi1/lun10-part1", "/data", auto, "defaults,nofail" ]

runcmd:
 - [ mkdir, /data/input ]
 - [ mkdir, /data/runs ] 
 - [ chown, -R, "azureuser:azureuser", /data ]

# This is the configuration for vdb-config of SRA Toolkit
# This should prevent having to run --interactively to have
# access to fasterq-dump
-   content: |
      /LIBS/GUID = "35a9977e-ac83-4b06-8751-ea61537984a7"
      /config/default = "false"
      /repository/user/ad/public/apps/file/volumes/flatAd = "."
      /repository/user/ad/public/apps/refseq/volumes/refseqAd = "."
      /repository/user/ad/public/apps/sra/volumes/sraAd = "."
      /repository/user/ad/public/apps/sraPileup/volumes/ad = "."
      /repository/user/ad/public/apps/sraRealign/volumes/ad = "."
      /repository/user/ad/public/root = "."
      /repository/user/default-path = "/home/azureuser/ncbi"
    path: /home/azureuser/.ncbi/user-settings.mkfg
