#cloud-config

package_upgrade: true

disk_setup:
  /dev/disk/azure/scsi1/lun10:
    table_type: 'gpt'
    layout:
      - 100
    overwrite: true

fs_setup:
  - label: data
    device: '/dev/disk/azure/scsi1/lun10'
    filesystem: 'ext4'
    partition: 1

mounts:
  - [ "/dev/disk/azure/scsi1/lun0-part1", "/data", auto, "defaults,noexec,nofail" ]

packages:
  - build-essential
