#cloud-config

package_upgrade: true

disk_setup:
  /dev/sdc:
    table_type: 'mbr'
    layout:
      - 100
    overwrite: true

fs_setup:
  - label: data
    filesystem: 'ext4'
    device: '/dev/sdc1'
    partition: auto

mounts:
  - [ sdc1, /data ]

packages:
  - build-essential
